language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - CONFIG_FILE=$(sudo -u postgres psql postgres -c "SHOW config_file;" -q -t | head -1)
  - 'CONFIG_FILE="${CONFIG_FILE:1}"'
  - echo "max_prepared_transactions = 10" | sudo tee -a "$CONFIG_FILE"
  - sudo cat "$CONFIG_FILE"
  - sudo service postgresql restart
  - sudo -u postgres createdb --owner=$USER zope_sqlalchemy_tests
  - pip install -U setuptools
install:
  - python bootstrap.py
  - bin/buildout -c postgres.cfg
script:
  - bin/test
  - bin/testpg
  - bin/testpg2
